import { supabase } from "@/integrations/supabase/client";
import { Database } from "@/integrations/supabase/types";

export type Player = Database['public']['Tables']['players']['Row'];

// Fallback data in case Supabase is not connected or table doesn't exist yet
const FALLBACK_PLAYERS: Player[] = [
  // TOP FORWARDS
  { id: '1', full_name: 'Connor McDavid', position: 'C', team: 'EDM', jersey_number: '97', status: 'active', goals: 32, assists: 100, points: 132, plus_minus: 35, shots: 263, hits: 29, blocks: 21, wins: null, losses: null, ot_losses: null, saves: null, goals_against_average: null, save_percentage: null, headshot_url: 'https://assets.nhle.com/mugs/nhl/20232024/EDM/8478402.png', last_updated: new Date().toISOString() },
  { id: '2', full_name: 'Nathan MacKinnon', position: 'C', team: 'COL', jersey_number: '29', status: 'active', goals: 51, assists: 89, points: 140, plus_minus: 35, shots: 405, hits: 45, blocks: 34, wins: null, losses: null, ot_losses: null, saves: null, goals_against_average: null, save_percentage: null, headshot_url: 'https://assets.nhle.com/mugs/nhl/20232024/COL/8477492.png', last_updated: new Date().toISOString() },
  { id: '3', full_name: 'Nikita Kucherov', position: 'RW', team: 'TBL', jersey_number: '86', status: 'active', goals: 44, assists: 100, points: 144, plus_minus: 8, shots: 306, hits: 25, blocks: 18, wins: null, losses: null, ot_losses: null, saves: null, goals_against_average: null, save_percentage: null, headshot_url: 'https://assets.nhle.com/mugs/nhl/20232024/TBL/8476453.png', last_updated: new Date().toISOString() },
  { id: '4', full_name: 'Auston Matthews', position: 'C', team: 'TOR', jersey_number: '34', status: 'active', goals: 69, assists: 38, points: 107, plus_minus: 31, shots: 369, hits: 90, blocks: 93, wins: null, losses: null, ot_losses: null, saves: null, goals_against_average: null, save_percentage: null, headshot_url: 'https://assets.nhle.com/mugs/nhl/20232024/TOR/8479318.png', last_updated: new Date().toISOString() },
  { id: '5', full_name: 'Leon Draisaitl', position: 'C', team: 'EDM', jersey_number: '29', status: 'active', goals: 41, assists: 65, points: 106, plus_minus: 26, shots: 217, hits: 40, blocks: 22, wins: null, losses: null, ot_losses: null, saves: null, goals_against_average: null, save_percentage: null, headshot_url: 'https://assets.nhle.com/mugs/nhl/20232024/EDM/8477934.png', last_updated: new Date().toISOString() },
  { id: '6', full_name: 'Artemi Panarin', position: 'LW', team: 'NYR', jersey_number: '10', status: 'active', goals: 49, assists: 71, points: 120, plus_minus: 16, shots: 303, hits: 17, blocks: 19, wins: null, losses: null, ot_losses: null, saves: null, goals_against_average: null, save_percentage: null, headshot_url: 'https://assets.nhle.com/mugs/nhl/20232024/NYR/8478550.png', last_updated: new Date().toISOString() },
  { id: '7', full_name: 'David Pastrnak', position: 'RW', team: 'BOS', jersey_number: '88', status: 'active', goals: 47, assists: 63, points: 110, plus_minus: 21, shots: 382, hits: 53, blocks: 25, wins: null, losses: null, ot_losses: null, saves: null, goals_against_average: null, save_percentage: null, headshot_url: 'https://assets.nhle.com/mugs/nhl/20232024/BOS/8477956.png', last_updated: new Date().toISOString() },
  { id: '8', full_name: 'J.T. Miller', position: 'C', team: 'VAN', jersey_number: '9', status: 'active', goals: 37, assists: 66, points: 103, plus_minus: 32, shots: 194, hits: 173, blocks: 60, wins: null, losses: null, ot_losses: null, saves: null, goals_against_average: null, save_percentage: null, headshot_url: 'https://assets.nhle.com/mugs/nhl/20232024/VAN/8476468.png', last_updated: new Date().toISOString() },
  { id: '9', full_name: 'Mikko Rantanen', position: 'RW', team: 'COL', jersey_number: '96', status: 'active', goals: 42, assists: 62, points: 104, plus_minus: 19, shots: 268, hits: 61, blocks: 46, wins: null, losses: null, ot_losses: null, saves: null, goals_against_average: null, save_percentage: null, headshot_url: 'https://assets.nhle.com/mugs/nhl/20232024/COL/8478420.png', last_updated: new Date().toISOString() },
  { id: '10', full_name: 'William Nylander', position: 'RW', team: 'TOR', jersey_number: '88', status: 'active', goals: 40, assists: 58, points: 98, plus_minus: 1, shots: 316, hits: 21, blocks: 28, wins: null, losses: null, ot_losses: null, saves: null, goals_against_average: null, save_percentage: null, headshot_url: 'https://assets.nhle.com/mugs/nhl/20232024/TOR/8477939.png', last_updated: new Date().toISOString() },
  { id: '11', full_name: 'Elias Pettersson', position: 'C', team: 'VAN', jersey_number: '40', status: 'active', goals: 34, assists: 55, points: 89, plus_minus: 20, shots: 207, hits: 71, blocks: 75, wins: null, losses: null, ot_losses: null, saves: null, goals_against_average: null, save_percentage: null, headshot_url: 'https://assets.nhle.com/mugs/nhl/20232024/VAN/8480012.png', last_updated: new Date().toISOString() },
  { id: '12', full_name: 'Matthew Tkachuk', position: 'RW', team: 'FLA', jersey_number: '19', status: 'active', goals: 26, assists: 62, points: 88, plus_minus: 19, shots: 269, hits: 152, blocks: 28, wins: null, losses: null, ot_losses: null, saves: null, goals_against_average: null, save_percentage: null, headshot_url: 'https://assets.nhle.com/mugs/nhl/20232024/FLA/8479314.png', last_updated: new Date().toISOString() },
  { id: '13', full_name: 'Sam Reinhart', position: 'RW', team: 'FLA', jersey_number: '13', status: 'active', goals: 57, assists: 37, points: 94, plus_minus: 29, shots: 233, hits: 56, blocks: 44, wins: null, losses: null, ot_losses: null, saves: null, goals_against_average: null, save_percentage: null, headshot_url: 'https://assets.nhle.com/mugs/nhl/20232024/FLA/8477933.png', last_updated: new Date().toISOString() },
  { id: '14', full_name: 'Connor Bedard', position: 'C', team: 'CHI', jersey_number: '98', status: 'active', goals: 22, assists: 39, points: 61, plus_minus: -44, shots: 206, hits: 47, blocks: 34, wins: null, losses: null, ot_losses: null, saves: null, goals_against_average: null, save_percentage: null, headshot_url: 'https://assets.nhle.com/mugs/nhl/20232024/CHI/8484144.png', last_updated: new Date().toISOString() },
  { id: '15', full_name: 'Jack Hughes', position: 'C', team: 'NJD', jersey_number: '86', status: 'injured', goals: 27, assists: 47, points: 74, plus_minus: -12, shots: 274, hits: 12, blocks: 19, wins: null, losses: null, ot_losses: null, saves: null, goals_against_average: null, save_percentage: null, headshot_url: 'https://assets.nhle.com/mugs/nhl/20232024/NJD/8481559.png', last_updated: new Date().toISOString() },
  { id: '16', full_name: 'Kirill Kaprizov', position: 'LW', team: 'MIN', jersey_number: '97', status: 'active', goals: 46, assists: 50, points: 96, plus_minus: 11, shots: 277, hits: 49, blocks: 29, wins: null, losses: null, ot_losses: null, saves: null, goals_against_average: null, save_percentage: null, headshot_url: 'https://assets.nhle.com/mugs/nhl/20232024/MIN/8478864.png', last_updated: new Date().toISOString() },
  { id: '17', full_name: 'Filip Forsberg', position: 'LW', team: 'NSH', jersey_number: '9', status: 'active', goals: 48, assists: 46, points: 94, plus_minus: 16, shots: 347, hits: 139, blocks: 42, wins: null, losses: null, ot_losses: null, saves: null, goals_against_average: null, save_percentage: null, headshot_url: 'https://assets.nhle.com/mugs/nhl/20232024/NSH/8476887.png', last_updated: new Date().toISOString() },
  { id: '18', full_name: 'Sidney Crosby', position: 'C', team: 'PIT', jersey_number: '87', status: 'active', goals: 42, assists: 52, points: 94, plus_minus: 7, shots: 278, hits: 62, blocks: 35, wins: null, losses: null, ot_losses: null, saves: null, goals_against_average: null, save_percentage: null, headshot_url: 'https://assets.nhle.com/mugs/nhl/20232024/PIT/8471675.png', last_updated: new Date().toISOString() },
  { id: '19', full_name: 'Brady Tkachuk', position: 'LW', team: 'OTT', jersey_number: '7', status: 'active', goals: 37, assists: 37, points: 74, plus_minus: -1, shots: 351, hits: 293, blocks: 21, wins: null, losses: null, ot_losses: null, saves: null, goals_against_average: null, save_percentage: null, headshot_url: 'https://assets.nhle.com/mugs/nhl/20232024/OTT/8480801.png', last_updated: new Date().toISOString() },
  { id: '20', full_name: 'Mitch Marner', position: 'RW', team: 'TOR', jersey_number: '16', status: 'active', goals: 26, assists: 59, points: 85, plus_minus: 21, shots: 212, hits: 32, blocks: 45, wins: null, losses: null, ot_losses: null, saves: null, goals_against_average: null, save_percentage: null, headshot_url: 'https://assets.nhle.com/mugs/nhl/20232024/TOR/8478483.png', last_updated: new Date().toISOString() },
  { id: '21', full_name: 'Sebastian Aho', position: 'C', team: 'CAR', jersey_number: '20', status: 'active', goals: 36, assists: 53, points: 89, plus_minus: 34, shots: 289, hits: 45, blocks: 23, wins: null, losses: null, ot_losses: null, saves: null, goals_against_average: null, save_percentage: null, headshot_url: 'https://assets.nhle.com/mugs/nhl/20232024/CAR/8478427.png', last_updated: new Date().toISOString() },
  { id: '22', full_name: 'Aleksander Barkov', position: 'C', team: 'FLA', jersey_number: '16', status: 'active', goals: 23, assists: 57, points: 80, plus_minus: 33, shots: 201, hits: 34, blocks: 45, wins: null, losses: null, ot_losses: null, saves: null, goals_against_average: null, save_percentage: null, headshot_url: 'https://assets.nhle.com/mugs/nhl/20232024/FLA/8477493.png', last_updated: new Date().toISOString() },
  { id: '23', full_name: 'Jack Eichel', position: 'C', team: 'VGK', jersey_number: '9', status: 'active', goals: 31, assists: 37, points: 68, plus_minus: 4, shots: 278, hits: 25, blocks: 41, wins: null, losses: null, ot_losses: null, saves: null, goals_against_average: null, save_percentage: null, headshot_url: 'https://assets.nhle.com/mugs/nhl/20232024/VGK/8478403.png', last_updated: new Date().toISOString() },
  { id: '24', full_name: 'Zach Hyman', position: 'LW', team: 'EDM', jersey_number: '18', status: 'active', goals: 54, assists: 23, points: 77, plus_minus: 36, shots: 290, hits: 45, blocks: 34, wins: null, losses: null, ot_losses: null, saves: null, goals_against_average: null, save_percentage: null, headshot_url: 'https://assets.nhle.com/mugs/nhl/20232024/EDM/8475791.png', last_updated: new Date().toISOString() },
  { id: '25', full_name: 'Jason Robertson', position: 'LW', team: 'DAL', jersey_number: '21', status: 'active', goals: 29, assists: 51, points: 80, plus_minus: 19, shots: 231, hits: 23, blocks: 19, wins: null, losses: null, ot_losses: null, saves: null, goals_against_average: null, save_percentage: null, headshot_url: 'https://assets.nhle.com/mugs/nhl/20232024/DAL/8479992.png', last_updated: new Date().toISOString() },
  { id: '26', full_name: 'Chris Kreider', position: 'LW', team: 'NYR', jersey_number: '20', status: 'active', goals: 39, assists: 36, points: 75, plus_minus: 19, shots: 245, hits: 123, blocks: 23, wins: null, losses: null, ot_losses: null, saves: null, goals_against_average: null, save_percentage: null, headshot_url: 'https://assets.nhle.com/mugs/nhl/20232024/NYR/8475184.png', last_updated: new Date().toISOString() },
  { id: '27', full_name: 'Brayden Point', position: 'C', team: 'TBL', jersey_number: '21', status: 'active', goals: 46, assists: 44, points: 90, plus_minus: 9, shots: 234, hits: 21, blocks: 23, wins: null, losses: null, ot_losses: null, saves: null, goals_against_average: null, save_percentage: null, headshot_url: 'https://assets.nhle.com/mugs/nhl/20232024/TBL/8477955.png', last_updated: new Date().toISOString() },
  { id: '28', full_name: 'Steven Stamkos', position: 'C', team: 'TBL', jersey_number: '91', status: 'active', goals: 40, assists: 41, points: 81, plus_minus: -21, shots: 262, hits: 89, blocks: 34, wins: null, losses: null, ot_losses: null, saves: null, goals_against_average: null, save_percentage: null, headshot_url: 'https://assets.nhle.com/mugs/nhl/20232024/TBL/8474564.png', last_updated: new Date().toISOString() },
  { id: '29', full_name: 'Adrian Kempe', position: 'RW', team: 'LAK', jersey_number: '9', status: 'active', goals: 28, assists: 47, points: 75, plus_minus: 13, shots: 246, hits: 112, blocks: 34, wins: null, losses: null, ot_losses: null, saves: null, goals_against_average: null, save_percentage: null, headshot_url: 'https://assets.nhle.com/mugs/nhl/20232024/LAK/8477960.png', last_updated: new Date().toISOString() },
  { id: '30', full_name: 'Lucas Raymond', position: 'RW', team: 'DET', jersey_number: '23', status: 'active', goals: 31, assists: 41, points: 72, plus_minus: -12, shots: 201, hits: 23, blocks: 23, wins: null, losses: null, ot_losses: null, saves: null, goals_against_average: null, save_percentage: null, headshot_url: 'https://assets.nhle.com/mugs/nhl/20232024/DET/8482078.png', last_updated: new Date().toISOString() },
  { id: '31', full_name: 'Robert Thomas', position: 'C', team: 'STL', jersey_number: '18', status: 'active', goals: 26, assists: 60, points: 86, plus_minus: 9, shots: 180, hits: 45, blocks: 45, wins: null, losses: null, ot_losses: null, saves: null, goals_against_average: null, save_percentage: null, headshot_url: 'https://assets.nhle.com/mugs/nhl/20232024/STL/8480023.png', last_updated: new Date().toISOString() },
  { id: '32', full_name: 'Clayton Keller', position: 'RW', team: 'UTA', jersey_number: '9', status: 'active', goals: 33, assists: 43, points: 76, plus_minus: -20, shots: 228, hits: 25, blocks: 34, wins: null, losses: null, ot_losses: null, saves: null, goals_against_average: null, save_percentage: null, headshot_url: 'https://assets.nhle.com/mugs/nhl/20232024/ARI/8479339.png', last_updated: new Date().toISOString() },
  { id: '33', full_name: 'Travis Konecny', position: 'RW', team: 'PHI', jersey_number: '11', status: 'active', goals: 33, assists: 35, points: 68, plus_minus: -5, shots: 241, hits: 89, blocks: 45, wins: null, losses: null, ot_losses: null, saves: null, goals_against_average: null, save_percentage: null, headshot_url: 'https://assets.nhle.com/mugs/nhl/20232024/PHI/8478439.png', last_updated: new Date().toISOString() },
  { id: '34', full_name: 'Bo Horvat', position: 'C', team: 'NYI', jersey_number: '14', status: 'active', goals: 33, assists: 35, points: 68, plus_minus: 8, shots: 248, hits: 56, blocks: 67, wins: null, losses: null, ot_losses: null, saves: null, goals_against_average: null, save_percentage: null, headshot_url: 'https://assets.nhle.com/mugs/nhl/20232024/NYI/8477500.png', last_updated: new Date().toISOString() },
  { id: '35', full_name: 'Mathew Barzal', position: 'C', team: 'NYI', jersey_number: '13', status: 'active', goals: 23, assists: 57, points: 80, plus_minus: -1, shots: 240, hits: 45, blocks: 34, wins: null, losses: null, ot_losses: null, saves: null, goals_against_average: null, save_percentage: null, headshot_url: 'https://assets.nhle.com/mugs/nhl/20232024/NYI/8478445.png', last_updated: new Date().toISOString() },
  { id: '36', full_name: 'Brock Boeser', position: 'RW', team: 'VAN', jersey_number: '6', status: 'active', goals: 40, assists: 33, points: 73, plus_minus: 23, shots: 209, hits: 45, blocks: 34, wins: null, losses: null, ot_losses: null, saves: null, goals_against_average: null, save_percentage: null, headshot_url: 'https://assets.nhle.com/mugs/nhl/20232024/VAN/8478444.png', last_updated: new Date().toISOString() },
  { id: '37', full_name: 'Alex Ovechkin', position: 'LW', team: 'WSH', jersey_number: '8', status: 'active', goals: 31, assists: 34, points: 65, plus_minus: -22, shots: 272, hits: 189, blocks: 45, wins: null, losses: null, ot_losses: null, saves: null, goals_against_average: null, save_percentage: null, headshot_url: 'https://assets.nhle.com/mugs/nhl/20232024/WSH/8471214.png', last_updated: new Date().toISOString() },
  { id: '38', full_name: 'Dylan Larkin', position: 'C', team: 'DET', jersey_number: '71', status: 'active', goals: 33, assists: 36, points: 69, plus_minus: 5, shots: 234, hits: 45, blocks: 34, wins: null, losses: null, ot_losses: null, saves: null, goals_against_average: null, save_percentage: null, headshot_url: 'https://assets.nhle.com/mugs/nhl/20232024/DET/8477946.png', last_updated: new Date().toISOString() },
  { id: '39', full_name: 'Nick Suzuki', position: 'C', team: 'MTL', jersey_number: '14', status: 'active', goals: 33, assists: 44, points: 77, plus_minus: -14, shots: 215, hits: 45, blocks: 56, wins: null, losses: null, ot_losses: null, saves: null, goals_against_average: null, save_percentage: null, headshot_url: 'https://assets.nhle.com/mugs/nhl/20232024/MTL/8480018.png', last_updated: new Date().toISOString() },
  { id: '40', full_name: 'Cole Caufield', position: 'RW', team: 'MTL', jersey_number: '22', status: 'active', goals: 28, assists: 37, points: 65, plus_minus: -4, shots: 314, hits: 34, blocks: 23, wins: null, losses: null, ot_losses: null, saves: null, goals_against_average: null, save_percentage: null, headshot_url: 'https://assets.nhle.com/mugs/nhl/20232024/MTL/8481540.png', last_updated: new Date().toISOString() },

  // DEFENSEMEN
  { id: '41', full_name: 'Quinn Hughes', position: 'D', team: 'VAN', jersey_number: '43', status: 'active', goals: 17, assists: 75, points: 92, plus_minus: 38, shots: 199, hits: 29, blocks: 56, wins: null, losses: null, ot_losses: null, saves: null, goals_against_average: null, save_percentage: null, headshot_url: 'https://assets.nhle.com/mugs/nhl/20232024/VAN/8480800.png', last_updated: new Date().toISOString() },
  { id: '42', full_name: 'Cale Makar', position: 'D', team: 'COL', jersey_number: '8', status: 'active', goals: 21, assists: 69, points: 90, plus_minus: 15, shots: 231, hits: 37, blocks: 148, wins: null, losses: null, ot_losses: null, saves: null, goals_against_average: null, save_percentage: null, headshot_url: 'https://assets.nhle.com/mugs/nhl/20232024/COL/8480069.png', last_updated: new Date().toISOString() },
  { id: '43', full_name: 'Roman Josi', position: 'D', team: 'NSH', jersey_number: '59', status: 'active', goals: 23, assists: 62, points: 85, plus_minus: 12, shots: 268, hits: 45, blocks: 151, wins: null, losses: null, ot_losses: null, saves: null, goals_against_average: null, save_percentage: null, headshot_url: 'https://assets.nhle.com/mugs/nhl/20232024/NSH/8474600.png', last_updated: new Date().toISOString() },
  { id: '44', full_name: 'Evan Bouchard', position: 'D', team: 'EDM', jersey_number: '2', status: 'active', goals: 18, assists: 64, points: 82, plus_minus: 34, shots: 234, hits: 45, blocks: 89, wins: null, losses: null, ot_losses: null, saves: null, goals_against_average: null, save_percentage: null, headshot_url: 'https://assets.nhle.com/mugs/nhl/20232024/EDM/8480803.png', last_updated: new Date().toISOString() },
  { id: '45', full_name: 'Noah Dobson', position: 'D', team: 'NYI', jersey_number: '8', status: 'active', goals: 10, assists: 60, points: 70, plus_minus: 12, shots: 189, hits: 34, blocks: 180, wins: null, losses: null, ot_losses: null, saves: null, goals_against_average: null, save_percentage: null, headshot_url: 'https://assets.nhle.com/mugs/nhl/20232024/NYI/8480865.png', last_updated: new Date().toISOString() },
  { id: '46', full_name: 'Victor Hedman', position: 'D', team: 'TBL', jersey_number: '77', status: 'active', goals: 13, assists: 63, points: 76, plus_minus: 18, shots: 187, hits: 45, blocks: 123, wins: null, losses: null, ot_losses: null, saves: null, goals_against_average: null, save_percentage: null, headshot_url: 'https://assets.nhle.com/mugs/nhl/20232024/TBL/8475167.png', last_updated: new Date().toISOString() },
  { id: '47', full_name: 'Adam Fox', position: 'D', team: 'NYR', jersey_number: '23', status: 'active', goals: 17, assists: 56, points: 73, plus_minus: 21, shots: 167, hits: 23, blocks: 112, wins: null, losses: null, ot_losses: null, saves: null, goals_against_average: null, save_percentage: null, headshot_url: 'https://assets.nhle.com/mugs/nhl/20232024/NYR/8479323.png', last_updated: new Date().toISOString() },
  { id: '48', full_name: 'Josh Morrissey', position: 'D', team: 'WPG', jersey_number: '44', status: 'active', goals: 10, assists: 59, points: 69, plus_minus: 34, shots: 187, hits: 45, blocks: 89, wins: null, losses: null, ot_losses: null, saves: null, goals_against_average: null, save_percentage: null, headshot_url: 'https://assets.nhle.com/mugs/nhl/20232024/WPG/8477498.png', last_updated: new Date().toISOString() },
  { id: '49', full_name: 'Morgan Rielly', position: 'D', team: 'TOR', jersey_number: '44', status: 'active', goals: 7, assists: 51, points: 58, plus_minus: 7, shots: 178, hits: 45, blocks: 98, wins: null, losses: null, ot_losses: null, saves: null, goals_against_average: null, save_percentage: null, headshot_url: 'https://assets.nhle.com/mugs/nhl/20232024/TOR/8476853.png', last_updated: new Date().toISOString() },
  { id: '50', full_name: 'Charlie McAvoy', position: 'D', team: 'BOS', jersey_number: '73', status: 'active', goals: 12, assists: 35, points: 47, plus_minus: 4, shots: 156, hits: 123, blocks: 145, wins: null, losses: null, ot_losses: null, saves: null, goals_against_average: null, save_percentage: null, headshot_url: 'https://assets.nhle.com/mugs/nhl/20232024/BOS/8479325.png', last_updated: new Date().toISOString() },
  { id: '51', full_name: 'Erik Karlsson', position: 'D', team: 'PIT', jersey_number: '65', status: 'active', goals: 11, assists: 45, points: 56, plus_minus: 4, shots: 201, hits: 34, blocks: 78, wins: null, losses: null, ot_losses: null, saves: null, goals_against_average: null, save_percentage: null, headshot_url: 'https://assets.nhle.com/mugs/nhl/20232024/PIT/8474578.png', last_updated: new Date().toISOString() },
  { id: '52', full_name: 'Rasmus Dahlin', position: 'D', team: 'BUF', jersey_number: '26', status: 'active', goals: 20, assists: 39, points: 59, plus_minus: -3, shots: 235, hits: 195, blocks: 154, wins: null, losses: null, ot_losses: null, saves: null, goals_against_average: null, save_percentage: null, headshot_url: 'https://assets.nhle.com/mugs/nhl/20232024/BUF/8480839.png', last_updated: new Date().toISOString() },
  { id: '53', full_name: 'John Carlson', position: 'D', team: 'WSH', jersey_number: '74', status: 'active', goals: 10, assists: 42, points: 52, plus_minus: -7, shots: 189, hits: 45, blocks: 189, wins: null, losses: null, ot_losses: null, saves: null, goals_against_average: null, save_percentage: null, headshot_url: 'https://assets.nhle.com/mugs/nhl/20232024/WSH/8474590.png', last_updated: new Date().toISOString() },
  { id: '54', full_name: 'Zach Werenski', position: 'D', team: 'CBJ', jersey_number: '8', status: 'active', goals: 11, assists: 46, points: 57, plus_minus: 0, shots: 202, hits: 23, blocks: 112, wins: null, losses: null, ot_losses: null, saves: null, goals_against_average: null, save_percentage: null, headshot_url: 'https://assets.nhle.com/mugs/nhl/20232024/CBJ/8478460.png', last_updated: new Date().toISOString() },
  { id: '55', full_name: 'Miro Heiskanen', position: 'D', team: 'DAL', jersey_number: '4', status: 'active', goals: 9, assists: 45, points: 54, plus_minus: -8, shots: 178, hits: 34, blocks: 89, wins: null, losses: null, ot_losses: null, saves: null, goals_against_average: null, save_percentage: null, headshot_url: 'https://assets.nhle.com/mugs/nhl/20232024/DAL/8480036.png', last_updated: new Date().toISOString() },
  { id: '56', full_name: 'Shea Theodore', position: 'D', team: 'VGK', jersey_number: '27', status: 'active', goals: 5, assists: 37, points: 42, plus_minus: 4, shots: 145, hits: 23, blocks: 67, wins: null, losses: null, ot_losses: null, saves: null, goals_against_average: null, save_percentage: null, headshot_url: 'https://assets.nhle.com/mugs/nhl/20232024/VGK/8477447.png', last_updated: new Date().toISOString() },
  { id: '57', full_name: 'Alex Pietrangelo', position: 'D', team: 'VGK', jersey_number: '7', status: 'active', goals: 4, assists: 29, points: 33, plus_minus: 2, shots: 134, hits: 45, blocks: 123, wins: null, losses: null, ot_losses: null, saves: null, goals_against_average: null, save_percentage: null, headshot_url: 'https://assets.nhle.com/mugs/nhl/20232024/VGK/8474565.png', last_updated: new Date().toISOString() },
  { id: '58', full_name: 'Devon Toews', position: 'D', team: 'COL', jersey_number: '7', status: 'active', goals: 12, assists: 38, points: 50, plus_minus: 28, shots: 167, hits: 34, blocks: 89, wins: null, losses: null, ot_losses: null, saves: null, goals_against_average: null, save_percentage: null, headshot_url: 'https://assets.nhle.com/mugs/nhl/20232024/COL/8478038.png', last_updated: new Date().toISOString() },
  { id: '59', full_name: 'Gustav Forsling', position: 'D', team: 'FLA', jersey_number: '42', status: 'active', goals: 10, assists: 29, points: 39, plus_minus: 56, shots: 156, hits: 67, blocks: 78, wins: null, losses: null, ot_losses: null, saves: null, goals_against_average: null, save_percentage: null, headshot_url: 'https://assets.nhle.com/mugs/nhl/20232024/FLA/8478009.png', last_updated: new Date().toISOString() },
  { id: '60', full_name: 'Aaron Ekblad', position: 'D', team: 'FLA', jersey_number: '5', status: 'active', goals: 4, assists: 14, points: 18, plus_minus: 27, shots: 98, hits: 67, blocks: 56, wins: null, losses: null, ot_losses: null, saves: null, goals_against_average: null, save_percentage: null, headshot_url: 'https://assets.nhle.com/mugs/nhl/20232024/FLA/8477932.png', last_updated: new Date().toISOString() },

  // GOALIES
  { id: '61', full_name: 'Connor Hellebuyck', position: 'G', team: 'WPG', jersey_number: '37', status: 'active', goals: null, assists: null, points: null, plus_minus: null, shots: null, hits: null, blocks: null, wins: 37, losses: 19, ot_losses: 4, saves: 1656, goals_against_average: 2.39, save_percentage: 0.921, headshot_url: 'https://assets.nhle.com/mugs/nhl/20232024/WPG/8476945.png', last_updated: new Date().toISOString() },
  { id: '62', full_name: 'Thatcher Demko', position: 'G', team: 'VAN', jersey_number: '35', status: 'injured', goals: null, assists: null, points: null, plus_minus: null, shots: null, hits: null, blocks: null, wins: 35, losses: 14, ot_losses: 2, saves: 1369, goals_against_average: 2.45, save_percentage: 0.918, headshot_url: 'https://assets.nhle.com/mugs/nhl/20232024/VAN/8477967.png', last_updated: new Date().toISOString() },
  { id: '63', full_name: 'Sergei Bobrovsky', position: 'G', team: 'FLA', jersey_number: '72', status: 'active', goals: null, assists: null, points: null, plus_minus: null, shots: null, hits: null, blocks: null, wins: 36, losses: 17, ot_losses: 4, saves: 1449, goals_against_average: 2.37, save_percentage: 0.915, headshot_url: 'https://assets.nhle.com/mugs/nhl/20232024/FLA/8475683.png', last_updated: new Date().toISOString() },
  { id: '64', full_name: 'Igor Shesterkin', position: 'G', team: 'NYR', jersey_number: '31', status: 'active', goals: null, assists: null, points: null, plus_minus: null, shots: null, hits: null, blocks: null, wins: 36, losses: 17, ot_losses: 2, saves: 1496, goals_against_average: 2.58, save_percentage: 0.913, headshot_url: 'https://assets.nhle.com/mugs/nhl/20232024/NYR/8478048.png', last_updated: new Date().toISOString() },
  { id: '65', full_name: 'Jeremy Swayman', position: 'G', team: 'BOS', jersey_number: '1', status: 'active', goals: null, assists: null, points: null, plus_minus: null, shots: null, hits: null, blocks: null, wins: 25, losses: 10, ot_losses: 8, saves: 1152, goals_against_average: 2.53, save_percentage: 0.916, headshot_url: 'https://assets.nhle.com/mugs/nhl/20232024/BOS/8480280.png', last_updated: new Date().toISOString() },
  { id: '66', full_name: 'Juuse Saros', position: 'G', team: 'NSH', jersey_number: '74', status: 'active', goals: null, assists: null, points: null, plus_minus: null, shots: null, hits: null, blocks: null, wins: 35, losses: 24, ot_losses: 5, saves: 1672, goals_against_average: 2.86, save_percentage: 0.906, headshot_url: 'https://assets.nhle.com/mugs/nhl/20232024/NSH/8477424.png', last_updated: new Date().toISOString() },
  { id: '67', full_name: 'Jake Oettinger', position: 'G', team: 'DAL', jersey_number: '29', status: 'active', goals: null, assists: null, points: null, plus_minus: null, shots: null, hits: null, blocks: null, wins: 35, losses: 14, ot_losses: 4, saves: 1345, goals_against_average: 2.72, save_percentage: 0.905, headshot_url: 'https://assets.nhle.com/mugs/nhl/20232024/DAL/8479979.png', last_updated: new Date().toISOString() },
  { id: '68', full_name: 'Stuart Skinner', position: 'G', team: 'EDM', jersey_number: '74', status: 'active', goals: null, assists: null, points: null, plus_minus: null, shots: null, hits: null, blocks: null, wins: 36, losses: 16, ot_losses: 5, saves: 1456, goals_against_average: 2.62, save_percentage: 0.905, headshot_url: 'https://assets.nhle.com/mugs/nhl/20232024/EDM/8479973.png', last_updated: new Date().toISOString() },
  { id: '69', full_name: 'Alexandar Georgiev', position: 'G', team: 'COL', jersey_number: '40', status: 'active', goals: null, assists: null, points: null, plus_minus: null, shots: null, hits: null, blocks: null, wins: 38, losses: 18, ot_losses: 5, saves: 1588, goals_against_average: 3.02, save_percentage: 0.897, headshot_url: 'https://assets.nhle.com/mugs/nhl/20232024/COL/8480382.png', last_updated: new Date().toISOString() },
  { id: '70', full_name: 'Joey Daccord', position: 'G', team: 'SEA', jersey_number: '35', status: 'active', goals: null, assists: null, points: null, plus_minus: null, shots: null, hits: null, blocks: null, wins: 19, losses: 18, ot_losses: 11, saves: 1234, goals_against_average: 2.46, save_percentage: 0.916, headshot_url: 'https://assets.nhle.com/mugs/nhl/20232024/SEA/8478916.png', last_updated: new Date().toISOString() }
];

export const PlayerService = {
  async getAllPlayers() {
    try {
      const { data, error } = await supabase
        .from('players')
        .select('*')
        .order('points', { ascending: false });
        
      if (error) throw error;
      if (!data || data.length === 0) return FALLBACK_PLAYERS;
      
      return data;
    } catch (error) {
      console.warn('Supabase error or empty data, using fallback players:', error);
      return FALLBACK_PLAYERS;
    }
  },

  async getPlayersByPosition(position: string) {
    try {
      const { data, error } = await supabase
        .from('players')
        .select('*')
        .eq('position', position)
        .order('points', { ascending: false });
        
      if (error) throw error;
      if (!data || data.length === 0) return FALLBACK_PLAYERS.filter(p => p.position === position);
      
      return data;
    } catch (error) {
      console.warn('Supabase error or empty data, using fallback players:', error);
      return FALLBACK_PLAYERS.filter(p => p.position === position);
    }
  },

  async searchPlayers(query: string) {
    try {
      const { data, error } = await supabase
        .from('players')
        .select('*')
        .ilike('full_name', `%${query}%`)
        .order('points', { ascending: false });
        
      if (error) throw error;
      if (!data || data.length === 0) return FALLBACK_PLAYERS.filter(p => p.full_name.toLowerCase().includes(query.toLowerCase()));
      
      return data;
    } catch (error) {
      console.warn('Supabase error or empty data, using fallback players:', error);
      return FALLBACK_PLAYERS.filter(p => p.full_name.toLowerCase().includes(query.toLowerCase()));
    }
  }
};
